### ISSUE TITLE
Удалить мусор

### ISSUE THREAD

**Issue by iketari** [frontend-park-mail-ru/2016_1_PoLiglot#5]
- [x] https://github.com/frontend-park-mail-ru/2016_1_PoLiglot/blob/master/templates/npm-debug.log
- [x] https://github.com/frontend-park-mail-ru/2016_1_PoLiglot/blob/master/public_html/css/red-line.svg~

Навести порядок нужно.

**Comment by sfilatov96** [comment]
удалил!)
